type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  photoUrl: String
  weight: Float
  fitnessGoals: String
}

type Exercise @table {
  name: String!
  muscleGroup: String!
  createdAt: Timestamp!
  description: String
  instructions: String
  equipment: String
}

type Routine @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
}

type RoutineExercise @table(key: ["routine", "exercise"]) {
  routine: Routine!
  exercise: Exercise!
  order: Int!
  sets: Int
  reps: Int
}

type WorkoutSession @table {
  user: User!
  routine: Routine
  workoutDate: Date!
  createdAt: Timestamp!
  durationMinutes: Int
  notes: String
}

type WorkoutSet @table {
  workoutSession: WorkoutSession!
  exercise: Exercise!
  setNumber: Int!
  reps: Int!
  weightKg: Float!
  createdAt: Timestamp!
  notes: String
}