
type User @table(name: "Users") {
  id: String! @pk
  name: String
  email: String! @unique
  workouts: [Workout] @map(from: "id", to: "userId")
  goals: [Goal] @map(from: "id", to: "userId")
}

type Workout @table(name: "Workouts") {
  id: String! @pk
  userId: String!
  date: Timestamp!
  exercise: String!
  sets: Int!
  reps: Int!
  weight: Float!
  user: User! @map(from: "userId", to: "id")
}

type Goal @table(name: "Goals") {
  id: String! @pk
  userId: String!
  title: String!
  target: Float!
  current: Float!
  unit: String!
  user: User! @map(from: "userId", to: "id")
}
